from __future__ import annotations

from .models import Objective, PortService, Scenario


def _objectives() -> list[Objective]:
    return [
        Objective(id="scan", title="扫描开放端口", description="建立目标主机的服务画像。"),
        Objective(id="web", title="调查 Web 服务", description="访问剧情站点并识别下一步调查方向。"),
        Objective(id="enumerate", title="枚举隐藏路径", description="在模拟 Web 服务中发现未公开路径。"),
        Objective(id="evidence", title="读取证据文件", description="读取剧情证据并提取训练身份。"),
        Objective(id="access", title="建立模拟访问", description="使用剧情中发现的凭据进入虚构 SSH 主机。"),
    ]


SCENARIOS: dict[str, Scenario] = {
    "abandoned-lab": Scenario(
        id="abandoned-lab",
        name="废弃研究所",
        subtitle="一座被紧急封存的生物研究设施仍在回应网络探测。",
        difficulty="入门",
        category="Web / Linux",
        target_ip="10.10.10.10",
        intro="雨水敲击着封锁区的金属外墙。研究所已经断电三年，但内部网络刚刚出现了心跳。",
        briefing="确认目标暴露面，追踪遗留研究日志，并进入模拟主机取得证据。所有动作都只发生在纸上靶场的虚构世界中。",
        objectives=_objectives(),
        services=[
            PortService(port=22, service="ssh", version="OpenSSH 8.2p1"),
            PortService(port=80, service="http", version="nginx 1.18"),
            PortService(port=443, service="https", version="nginx 1.18"),
            PortService(port=3306, service="mysql", version="MySQL 8.0"),
        ],
        hints=[
            "先建立服务画像。你可以说“扫描所有 TCP 端口”，也可以输入 nmap -p- 10.10.10.10。",
            "开放端口里有 Web 服务。先访问主页，观察页面留下了什么调查方向。",
            "主页没有直接给出答案。尝试枚举隐藏目录或路径。",
            "枚举结果里出现了证据文件。读取它，而不是直接猜登录口令。",
            "证据已经给出训练账户。最后一步是完成模拟 SSH 验证。",
        ],
        web_observation="主页只有一张停工通知，但 HTML 注释写着：归档系统没有迁移，旧路径仍可能被索引。",
        hidden_paths=["/archive/", "/assets/", "/archive/shift-note.txt"],
        evidence_path="/archive/shift-note.txt",
        evidence_text="夜班账号 lab-intern；应急口令 inferno-042。该身份只存在于纸上靶场。",
        ssh_user="lab-intern",
        ssh_password="inferno-042",
        flag="FLAG{paper_range_first_breach}",
    ),
    "corp-intranet": Scenario(
        id="corp-intranet",
        name="企业内网残影",
        subtitle="一次演练结束后，隔离办公网里仍残留异常服务。",
        difficulty="进阶",
        category="Intranet / Service Discovery",
        target_ip="10.20.30.15",
        intro="凌晨两点，演练平台本应完全关闭，但一台资产仍持续广播心跳。你的任务是解释它为什么还活着。",
        briefing="枚举虚构办公网主机、检查内部站点、追踪演练记录并获取一次性训练身份。",
        objectives=_objectives(),
        services=[
            PortService(port=22, service="ssh", version="OpenSSH 9.0"),
            PortService(port=8080, service="http-proxy", version="Caddy 2.7"),
            PortService(port=8443, service="https-alt", version="Caddy 2.7"),
        ],
        hints=[
            "先确认主机还暴露了哪些服务。服务发现是解释异常资产的第一步。",
            "注意 8080/8443 这样的替代 Web 端口；先检查内部站点。",
            "内部首页只给出工单编号。继续枚举站点中的隐藏路径。",
            "找到演练工单文件后读取内容，确认临时身份。",
            "使用证据中的一次性训练身份完成模拟登录。",
        ],
        web_observation="内部告警页显示 DRILL-731 已结束，但页面脚注引用了未公开的 /ops/ 存档。",
        hidden_paths=["/ops/", "/ops/drill-731.txt", "/healthz"],
        evidence_path="/ops/drill-731.txt",
        evidence_text="演练账户 range-ops；一次性训练口令 ember-731，仅适用于本模拟世界。",
        ssh_user="range-ops",
        ssh_password="ember-731",
        flag="FLAG{ghost_in_the_intranet}",
    ),
    "underground-market": Scenario(
        id="underground-market",
        name="地下交易市场",
        subtitle="匿名交易节点在封闭网络里重新上线，等待调查。",
        difficulty="困难",
        category="Web / Narrative Recon",
        target_ip="172.16.66.6",
        intro="红色霓虹从排水隧道尽头闪烁。一个只存在于模拟网络的交易节点重新出现。",
        briefing="建立服务画像、追踪留言板维护痕迹、读取剧情证据并取得节点访问证明。",
        objectives=_objectives(),
        services=[
            PortService(port=22, service="ssh", version="Dropbear 2022.83"),
            PortService(port=8000, service="http-alt", version="uvicorn"),
            PortService(port=9001, service="tor-orport", version="simulated relay"),
        ],
        hints=[
            "不要先猜剧情。先做侦察，确认节点真正暴露了什么。",
            "交易节点的 Web 服务不在标准 80 端口，但 Web 调查动作仍会解析到当前场景。",
            "留言板首页没有凭据。尝试枚举维护相关的隐藏路径。",
            "读取维护记录，区分真正的训练身份和页面上的诱饵文本。",
            "使用维护记录中的训练账户完成最后验证。",
        ],
        web_observation="留言板只有几条过期交易信息，但底部维护脚本引用了 /board/maintenance/。",
        hidden_paths=["/board/", "/board/maintenance/", "/board/maintenance/night.txt"],
        evidence_path="/board/maintenance/night.txt",
        evidence_text="维护用户 broker-watch；训练密码 crimson-909。留言注明：仅用于纸上靶场。",
        ssh_user="broker-watch",
        ssh_password="crimson-909",
        flag="FLAG{market_after_midnight}",
    ),
    "municipal-archive": Scenario(
        id="municipal-archive",
        name="市政档案馆断电夜",
        subtitle="断电后的档案馆仍有一台数字化节点在独自运行。",
        difficulty="入门",
        category="Web / Evidence Trail",
        target_ip="10.44.7.23",
        intro="暴雨让老城区停电。档案馆的大厅一片漆黑，但地下数字化机房仍有一盏蓝灯没有熄灭。",
        briefing="确认数字化节点暴露面，找到未归档的迁移记录，并验证剧情中的维护身份。",
        objectives=_objectives(),
        services=[
            PortService(port=22, service="ssh", version="OpenSSH 8.9"),
            PortService(port=8088, service="http-alt", version="Apache httpd 2.4"),
        ],
        hints=[
            "先扫描，不要从故事文本猜端口。",
            "发现 Web 服务后先访问首页，确认系统用途。",
            "首页提示旧迁移面板还在，继续做路径枚举。",
            "读取迁移记录，提取维护账户。",
            "用证据里的训练身份完成模拟访问。",
        ],
        web_observation="数字化首页停在“迁移 87%”，页面源注释提到旧版迁移面板未从 /migration/ 清理。",
        hidden_paths=["/migration/", "/migration/queue.txt", "/migration/night-shift.log"],
        evidence_path="/migration/night-shift.log",
        evidence_text="夜班维护账号 archive-night；训练口令 folio-287。迁移记录明确标注为模拟演练数据。",
        ssh_user="archive-night",
        ssh_password="folio-287",
        flag="FLAG{archives_never_sleep}",
    ),
    "orbital-relay": Scenario(
        id="orbital-relay",
        name="轨道中继站静默协议",
        subtitle="地面测试网中的卫星中继模拟器突然停止上报遥测。",
        difficulty="进阶",
        category="Ops / Telemetry",
        target_ip="192.168.77.12",
        intro="凌晨四点，轨道通信实验室的测试大屏只剩一条红线：RELAY-12 LOST TELEMETRY。",
        briefing="调查封闭测试网中的中继模拟器，定位停更的遥测记录并恢复训练访问链。",
        objectives=_objectives(),
        services=[
            PortService(port=22, service="ssh", version="OpenSSH 9.3"),
            PortService(port=7000, service="http-alt", version="relay-console"),
            PortService(port=9100, service="metrics", version="simulated exporter"),
        ],
        hints=[
            "从服务画像开始，先确定控制台和遥测端口。",
            "访问模拟控制台，查看最后一次遥测同步提示。",
            "控制台引用了诊断目录，继续枚举路径。",
            "读取诊断快照，获取故障班次使用的训练身份。",
            "验证训练身份即可结束战役。",
        ],
        web_observation="控制台显示最后同步时间停在 03:17，并提示自动诊断结果写入 /diagnostics/。",
        hidden_paths=["/diagnostics/", "/diagnostics/last-sync.txt", "/diagnostics/crew.note"],
        evidence_path="/diagnostics/crew.note",
        evidence_text="故障班次账户 relay-tech；训练口令 apogee-317。该账户仅用于封闭模拟器。",
        ssh_user="relay-tech",
        ssh_password="apogee-317",
        flag="FLAG{silent_orbit_relay}",
    ),
    "night-freight": Scenario(
        id="night-freight",
        name="赤港夜班货运站",
        subtitle="自动化货运调度节点在封站后仍不断生成幽灵任务。",
        difficulty="困难",
        category="Industrial / Narrative Ops",
        target_ip="172.20.13.37",
        intro="港区已经封站，吊机都停了下来。但调度屏每隔九十秒仍会生成一张不存在的装卸单。",
        briefing="追踪幽灵调度任务的来源，找到班次记录，并验证隐藏在剧情证据里的值班身份。",
        objectives=_objectives(),
        services=[
            PortService(port=22, service="ssh", version="OpenSSH 9.1"),
            PortService(port=8080, service="http-proxy", version="dispatch-ui"),
            PortService(port=9200, service="event-index", version="simulated index"),
        ],
        hints=[
            "先确认调度节点对外暴露的服务，不要直接寻找所谓‘幽灵任务’。",
            "访问调度 UI，观察任务是从哪个子系统导入的。",
            "页面提到夜班缓存目录。使用路径枚举找到对应记录。",
            "读取夜班缓存中的交接文件，提取训练身份。",
            "使用交接文件中的身份完成模拟 SSH 验证。",
        ],
        web_observation="调度 UI 显示幽灵任务来源为 LEGACY-NIGHT-CACHE，并留下路径前缀 /handover/。",
        hidden_paths=["/handover/", "/handover/cache-index.json", "/handover/night-crew.txt"],
        evidence_path="/handover/night-crew.txt",
        evidence_text="交接用户 freight-night；训练口令 gantry-913。记录注明：非真实生产凭据。",
        ssh_user="freight-night",
        ssh_password="gantry-913",
        flag="FLAG{red_harbor_ghost_shift}",
    ),
}


def list_scenarios() -> list[Scenario]:
    return list(SCENARIOS.values())
